version: '3.8'
services:
  kestra:
    image: kestra/kestra:latest
    ports:
      - "8080:8080"
    environment:
      KESTRA_CONFIGURATION_PATH: "/app/config/application.yml"
      KESTRA_SERVER_PORT: "8080"
      KESTRA_SERVER_HOST: "0.0.0.0"
      KESTRA_STORAGE_TYPE: "local"
      KESTRA_STORAGE_LOCAL_BASE_PATH: "/tmp/kestra"
    volumes:
      - ./kestra/config:/app/config
      - ./kestra/flows:/app/flows
      - kestra_data:/tmp/kestra

volumes:
  kestra_data: