version: '3'
services:
  kestra:
    image: kestra/kestra:latest-full
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          repository:
            type: postgres
          queue:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/tmp/kestra-storage"
          jdbc:
            url: jdbc:postgresql://postgres:5432/kestra
            username: kestra
            password: k3str4
      KESTRA_PLUGINS: |
        - io.kestra.plugin:plugin-notifications:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      POSTGRES_DB: kestra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: